apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
       
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              key: username
              name: mongo-secret
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongo-secret
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              key: mongo-url
              name: mongo-config